### ISSUE TITLE
e1l2 - When a player takes a sniper rifle, the M1 Garand is replaced by it and disappears

### ISSUE THREAD

**Issue by ChannelDaniila** [HaZardModding/hzm-mohaa-coop-mod#110]

**Comment by 1337Smithy** [comment]
Not a bug, this is intended.

**Comment by ChannelDaniila** [comment]
In original BT you have M1 Garand and Sniper Rifle.

**Comment by 1337Smithy** [comment]
Can you please not reopen this. I'm aware of how it works in sp, but due to the way the code for giving players weapons works (we spawn weapons in and force players to pick them up), and because both weapons are of class rifle, I swap them out otherwise you'd just get more m1 garand ammo.
