### ISSUE TITLE
e1l1 - Bunker Explosion killing players but not respawning outside

### ISSUE THREAD

**Issue by Chrissstrahl** [HaZardModding/hzm-mohaa-coop-mod#111]
When bunker blowsup players killed inside respawn inside not outside as they should.
 As a consequence they get stuck inside.
Version released in october was used.
This could already be fixed and needs proper testing.

**Comment by ChannelDaniila** [comment]
Maybe you mean e1l2? I don't remember any explosions in bunkers on e1l1.

**Comment by ChannelDaniila** [comment]
Bug fixed.
