### ISSUE TITLE
m6l3a - Train doesn't move.

### ISSUE THREAD

**Issue by Crimewavezz** [HaZardModding/hzm-mohaa-coop-mod#116]
Fresh install of MoH and Co-Op. After joining the m6l3a from multiplayer menu, player spawns in map, then after joining allies team, train should start moving towards the base, it doesn't happen.
[qconsole.log](https://github.com/HaZardModding/hzm-mohaa-coop-mod/files/6683020/qconsole.log)

**Comment by 1337Smithy** [comment]
Fixed already: https://github.com/HaZardModding/hzm-mohaa-coop-mod/issues/69

**Comment by Crimewavezz** [comment]
Contacted with smithy, turns out I was using dec 21 release.
