### ISSUE TITLE
m4l1 - If pilot is dead, message not showing and level is not restarting

### ISSUE THREAD

**Issue by ChannelDaniila** [HaZardModding/hzm-mohaa-coop-mod#117]
![pilot_corpse1](https://user-images.githubusercontent.com/75738095/123787578-aa397480-d8e3-11eb-859d-5231742d46fb.png)

**Comment by ChannelDaniila** [comment]
Previously, this bug did not exist, now it has appeared for some reason.

**Comment by Chrissstrahl** [comment]
Could not reproduce, more details are needed. @ChannelDaniila

**Comment by ChannelDaniila** [comment]
![image](https://user-images.githubusercontent.com/75738095/142609533-cda25254-f85d-4c79-86f6-96543c5838d7.png)
The pilot has just been killed and the message has not appeared.

**Comment by Chrissstrahl** [comment]
More details on how to reproduce this would help!
Was it on a listen or dedicated server.
How many players ?
Did a player leave ?

**Comment by ChannelDaniila** [comment]
It was on our coop.hazardmodding.com server
Only me

**Comment by Chrissstrahl** [comment]
fixed
