### ISSUE TITLE
m4l3 - Player staying in truck with invisible shotgun

### ISSUE THREAD

**Issue by ChannelDaniila** [HaZardModding/hzm-mohaa-coop-mod#119]
When the mission has just begun, and you are eating in the back of a truck, you will have an invisible shotgun in your hands.

**Comment by ChannelDaniila** [comment]
![picture](https://user-images.githubusercontent.com/75738095/123790187-b541d400-d8e6-11eb-9a27-8e7b469f215d.png)

**Comment by 1337Smithy** [comment]
Eating in the back of the truck? What do you mean? Can you use the shotgun?

**Comment by ChannelDaniila** [comment]
No. In original game you can't use any weapons here and you don't have crosshair here too.

**Comment by ChannelDaniila** [comment]
When the player got into the truck without holstering the weapon, the sight, name and number of cartridges of the weapon will be visible. Or, if the level starts in a truck, then there is a chance that the weapon will not hide either, but will simply become transparent and not working.

**Comment by ChannelDaniila** [comment]
![image](https://user-images.githubusercontent.com/75738095/142610410-22b8c165-eafb-4c55-9a3b-008b4e3acdfa.png)
The player still spawn with a shotgun in hand.

**Comment by 1337Smithy** [comment]
Yep I'm aware you can't use weapons, was asking to clarify if you can now which would be a bug. But instead it's just an extremely minor cosmetic byproduct of the mission being MP now, and weapons being given to players at start of mission which probably was done for convenience. Not really a bug.

**Comment by Chrissstrahl** [comment]
Lets focus on important bugs and making more levels playable.
If we want to fix every minor bug or issue we will be working a year on the mod with no real progress.
