### ISSUE TITLE
Whole game - Character speech sometimes duplicate

### ISSUE THREAD

**Issue by ChannelDaniila** [HaZardModding/hzm-mohaa-coop-mod#128]
![изображение](https://user-images.githubusercontent.com/75738095/145693576-7b74e7e4-622b-40b4-89bf-a5ec4d632101.png)
Very old bug, and very annoying.

**Comment by ChannelDaniila** [comment]
By the way, this "duplicating" skipping some words too.

**Comment by ChannelDaniila** [comment]
![изображение](https://user-images.githubusercontent.com/75738095/145694117-865de7c7-63fb-4992-a49d-9bacb70f3442.png)

**Comment by Chrissstrahl** [comment]
this is a gamecode or engine, client or network glitch.
has nothing to to with the mod, we don't think there is a real easy solution for this, so nothing we can do.
