### ISSUE TITLE
Whole game - Sometimes when killing enemy, dying animation and sound can be repeated 5-10 times

### ISSUE THREAD

**Issue by ChannelDaniila** [HaZardModding/hzm-mohaa-coop-mod#130]
Sadly i can't show this.

**Comment by ChannelDaniila** [comment]
![изображение](https://user-images.githubusercontent.com/75738095/145709611-9be6f19d-1211-4b97-86b4-17c281d7d25e.png)

**Comment by Chrissstrahl** [comment]
we already has this issue reported and smithy explained that there is nothing we can do.
please don't reopen this again

**Comment by ChannelDaniila** [comment]
Sorry, i didn't saw
