### ISSUE TITLE
Global - Characters may repeat their phrases

### ISSUE THREAD

**Issue by LtJoeBaylor** [HaZardModding/hzm-mohaa-coop-mod#145]
For example in m1l1 one of the soldiers may repeat the "Ambush!".

![image](https://github.com/HaZardModding/hzm-mohaa-coop-mod/assets/75738095/b01a1ea4-db41-4501-ae6a-aadc034cc904)

**Comment by 1337Smithy** [comment]
Please, please, please stop duplicating this issue that has already been answered: https://github.com/HaZardModding/hzm-mohaa-coop-mod/issues/128#issuecomment-998500274
