### ISSUE TITLE
Global - Dying enemies can repeat animation and death sound

### ISSUE THREAD

**Issue by LtJoeBaylor** [HaZardModding/hzm-mohaa-coop-mod#148]
https://github.com/HaZardModding/hzm-mohaa-coop-mod/assets/75738095/07c7c5a2-7edc-4e4c-8df0-f58b39850618

**Comment by 1337Smithy** [comment]
As mentioned previously, see: https://github.com/HaZardModding/hzm-mohaa-coop-mod/issues/128#issuecomment-998500274
