### ISSUE TITLE
m5l1a & m5l1b - If someone survives the first part of the mission, they do not proceed to the second part of the mission

### ISSUE THREAD

**Issue by LtJoeBaylor** [HaZardModding/hzm-mohaa-coop-mod#155]
For example, in the original single-player game, I managed to rescue two rangers, and they successfully "moved on" to the second part of the mission.

![image](https://github.com/HaZardModding/hzm-mohaa-coop-mod/assets/75738095/839e2ecd-7239-4c4b-84a3-bf0e9507bc2b)

**Comment by 1337Smithy** [comment]
This is engine related. The scripts have access to a "game" object that is used to pass data between level transitions, but this doesn't work in MP. Probably not something we'll look into tbh.
