### ISSUE TITLE
e1l4 - Gates have no textures

### ISSUE THREAD

**Issue by LtJoeBaylor** [HaZardModding/hzm-mohaa-coop-mod#158]
What we see in MP:

![image](https://github.com/HaZardModding/hzm-mohaa-coop-mod/assets/75738095/aca01543-a12a-4941-9d90-34804d319b30)

How it should be (SP):

![image](https://github.com/HaZardModding/hzm-mohaa-coop-mod/assets/75738095/e26f2fa2-ede6-41fe-b591-a7b2b4865488)

**Comment by 1337Smithy** [comment]
This was answered here: https://github.com/HaZardModding/hzm-mohaa-coop-mod/issues/93#issuecomment-753546691 

While we appreciate the effort, please don't duplicate issues.

**Comment by 1337Smithy** [comment]
Closed.
