### ISSUE TITLE
Global - Responses from pilots on the radio are duplicated, depending on the number of players on the server

### ISSUE THREAD

**Issue by LtJoeBaylor** [HaZardModding/hzm-mohaa-coop-mod#161]
Response from the pilots are duplicating, **one player = 1 response. Two players = 2 responses at the same time** (and everyone hears them). If there are many players, it can be very loud. Many people have already told me how much they dislike it, although it's not something critical.

https://github.com/HaZardModding/hzm-mohaa-coop-mod/assets/75738095/cf4422dd-9742-407a-acfb-a7fe8c7cd7b5

**Comment by 1337Smithy** [comment]
As mentioned previously, see: https://github.com/HaZardModding/hzm-mohaa-coop-mod/issues/128#issuecomment-998500274)
