### ISSUE TITLE
Players are given american_army skin by default

### ISSUE THREAD

**Issue by 1337Smithy** [HaZardModding/hzm-mohaa-coop-mod#56]
Players would be given american_army uniforms on every spawn when not in disguise (so, most missions) due to the way I coded the item handler. This was intentional as a quick fix to stop enemy uniforms carrying over to other maps. 

I've now put in a fix that should give players back their original uniforms (if possible - i.e. we know about it and they are still in server). If they try to connect with an enemy uniform on non-disguise portions, we just default to "american_army" again. 

This enhancement was very quickly put together, so needs plenty of testing: https://github.com/Chrissstrahl/hzm-mohaa-coop-mod/commit/198c1e4a08306ef5711211e316dfb39ee9f6d398

Note: the way it worked previously is I would just change their skin on spawn to american_army, so tiks of selected skins were still cached.

**Comment by 1337Smithy** [comment]
Reinstated old version. If we decided to implement this in future, it can be done so after next release if it passes rigorous testing.

**Comment by ChannelDaniila** [comment]
We have already added the function of changing the player skin.
