### ISSUE TITLE
e1l3 - Boat explosion not not reproduced.

### ISSUE THREAD

**Issue by ChannelDaniila** [HaZardModding/hzm-mohaa-coop-mod#64]
The boat explodes, but only by script. The explosion itself is absent.
![Image](https://user-images.githubusercontent.com/75738095/103171258-6fcb1e00-4853-11eb-92ce-4aa8aa61c4fa.png)

**Comment by 1337Smithy** [comment]
This isn't necessarily a bug, but a BT engine feature to cut down on effects in a level. In particularly busy levels BT will cut short or stop many explosive effects.

**Comment by Chrissstrahl** [comment]
> 
> 
> This isn't necessarily a bug, but a BT engine feature to cut down on effects in a level. In particularly busy levels BT will cut short or stop many explosive effects.

I think so too, I would close it as it is nothing that we can really change.
