### ISSUE TITLE
e1l3 - Ending disguise segment won't work if you reload from checkpoint

### ISSUE THREAD

**Issue by 1337Smithy** [HaZardModding/hzm-mohaa-coop-mod#65]
If your disguise is blown and the mission fails and reloads at checkpoint, Klaus does nothing and you cannot retry.

**Comment by 1337Smithy** [comment]
I need to prioritise this task. Not had time last couple of days, but hopefully will this weekend. The truck sequence doesn't want to play ball like the other missions, so will need extra time. I genuinely do blame Mackey and his terrible script. It's a plate of spaghetti, but without the nice things like meatballs and Bolognese sauce.

**Comment by 1337Smithy** [comment]
https://github.com/Chrissstrahl/hzm-mohaa-coop-mod/commit/2e938c30afb5051f627791584dcd3581b745b740

Needs testing as I couldn't replicate on my local. I did improve the code though, so maybe I fixed it?

**Comment by ChannelDaniila** [comment]
Tested. Fix is working. But delete uniform here: 
![Image](https://user-images.githubusercontent.com/75738095/103465523-1ed09380-4d45-11eb-881a-075206d9c05e.png)

**Comment by 1337Smithy** [comment]
Uniform is gone, but issue still persists. Looks like it happens when more than one player is connected. Weird.

**Comment by ChannelDaniila** [comment]
Fix is working fine.

**Comment by ChannelDaniila** [comment]
With 2+ players fix not working.

**Comment by Chrissstrahl** [comment]
Maybe we are hitting some sort of limitation when loading with a checkpoint and some stuff might be skipped.
Maybe braking up some code and have it executed delayed or in line/serial rather than parallel might fix it, this would also fix the issue if it is a parallelisation issue.

**Comment by Chrissstrahl** [comment]
I have disabled that savepoint, if players fail the previous savepoint is loadad, which isn't to much behind.
Needs to be tested
